import { Property, Testimonial } from './types';

export const DUMMY_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Modern 2BHK Apartment',
    location: 'Rajpur Road, Dehradun',
    price: 45000,
    priceLabel: 'month',
    type: 'Rental',
    listingType: 'Rent',
    bhk: '2BHK',
    area: 950,
    areaUnit: 'sqft',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800',
    badges: ['Rent', 'Verified'],
    isVerified: true,
    isNew: true,
    description: 'Beautiful semi-furnished apartment in the heart of Rajpur Road.',
    amenities: ['Parking', 'Lift', 'Security', 'Gym'],
    features: [{ label: 'Floor', value: '3rd' }, { label: 'Furnished', value: 'Semi' }],
    seller: { name: 'Amit Sharma', type: 'Owner', avatar: '', verified: true }
  },
  {
    id: '2',
    title: 'Premium 3BHK Builder Floor',
    location: 'GMS Road, Dehradun',
    price: 8500000,
    priceLabel: 'total',
    type: 'Residential',
    listingType: 'Buy',
    bhk: '3BHK',
    area: 1450,
    areaUnit: 'sqft',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800',
    badges: ['Sale', 'Hot'],
    isVerified: true,
    isHot: true,
    description: 'Spacious builder floor with modern fittings and large balconies.',
    amenities: ['Power Backup', 'Water Storage', 'Security'],
    features: [{ label: 'Status', value: 'Ready to Move' }, { label: 'Facing', value: 'East' }],
    seller: { name: 'BuildCon Builders', type: 'Builder', avatar: '', verified: true }
  },
  {
    id: '3',
    title: 'Co-working Studio Workspace',
    location: 'IT Park, Dehradun',
    price: 8000,
    priceLabel: 'month',
    type: 'Commercial',
    listingType: 'Rent',
    area: 200,
    areaUnit: 'sqft',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800',
    badges: ['Commercial', 'Verified'],
    isVerified: true,
    description: 'Fully equipped co-working space with high-speed internet.',
    amenities: ['WiFi', 'AC', 'Cafeteria', 'Meeting Rooms'],
    features: [{ label: 'Access', value: '24/7' }, { label: 'Seats', value: '1' }],
    seller: { name: 'SmartDesk', type: 'Agent', avatar: '', verified: true }
  },
  {
    id: '4',
    title: 'Residential Plot in Sahastradhara',
    location: 'Sahastradhara Road, Dehradun',
    price: 5500000,
    priceLabel: 'total',
    type: 'Plot',
    listingType: 'Buy',
    area: 1800,
    areaUnit: 'sqft',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800',
    badges: ['Plot', 'Verified'],
    isVerified: true,
    isNew: true,
    description: 'Level land in a prime residential locality with clear views.',
    amenities: ['Internal Road', 'Electricity', 'Water Connection'],
    features: [{ label: 'Zone', value: 'Residential' }, { label: 'Facing', value: 'South' }],
    seller: { name: 'Landmark Real Estate', type: 'Agent', avatar: '', verified: true }
  },
  {
    id: '5',
    title: 'Luxury 4BHK Villa',
    location: 'Vasant Vihar, Dehradun',
    price: 12000000,
    priceLabel: 'total',
    type: 'Residential',
    listingType: 'Buy',
    bhk: '4BHK',
    area: 2200,
    areaUnit: 'sqft',
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800',
    badges: ['Villa', 'Premium'],
    isVerified: true,
    description: 'High-end villa with a private garden and servant quarters.',
    amenities: ['Club House', 'Swimming Pool', 'Garden'],
    features: [{ label: 'Possession', value: 'Ready' }, { label: 'Age', value: 'New' }],
    seller: { name: 'Priya Verma', type: 'Owner', avatar: '', verified: true }
  },
  {
    id: '6',
    title: 'Compact 1BHK in Prem Nagar',
    location: 'Prem Nagar, Dehradun',
    price: 12000,
    priceLabel: 'month',
    type: 'Rental',
    listingType: 'Rent',
    bhk: '1BHK',
    area: 420,
    areaUnit: 'sqft',
    image: 'https://images.unsplash.com/photo-1630699144867-37acec97df5a?auto=format&fit=crop&q=80&w=800',
    badges: ['Rent', 'Budget'],
    isVerified: true,
    description: 'Affordable 1BHK near universities, perfect for students.',
    amenities: ['24/7 Water', 'Internet Ready'],
    features: [{ label: 'Floor', value: '1st' }, { label: 'Furnishing', value: 'Unfurnished' }],
    seller: { name: 'Rahul Bisht', type: 'Owner', avatar: '', verified: false }
  },
  {
    id: '7',
    title: 'Prime Retail Shop',
    location: 'Paltan Bazaar, Dehradun',
    price: 75000,
    priceLabel: 'month',
    type: 'Commercial',
    listingType: 'Rent',
    area: 500,
    areaUnit: 'sqft',
    image: 'https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?auto=format&fit=crop&q=80&w=800',
    badges: ['Shop', 'Hot'],
    isVerified: true,
    isHot: true,
    description: 'High-footfall retail space in the main market area.',
    amenities: ['Main Road Facing', 'Security'],
    features: [{ label: 'Frontage', value: '15 ft' }, { label: 'Floor', value: 'Ground' }],
    seller: { name: 'Market Properties', type: 'Agent', avatar: '', verified: true }
  },
  {
    id: '8',
    title: 'Green View Apartment 2BHK',
    location: 'Mussoorie Diversion, Dehradun',
    price: 35000,
    priceLabel: 'month',
    type: 'Rental',
    listingType: 'Rent',
    bhk: '2BHK',
    area: 1100,
    areaUnit: 'sqft',
    image: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80&w=800',
    badges: ['Rent', 'New'],
    isVerified: true,
    isNew: true,
    description: 'Modern apartment with stunning mountain views.',
    amenities: ['Club House', 'Gym', 'Parking', 'Kids Play Area'],
    features: [{ label: 'Floor', value: '5th' }, { label: 'Furnishing', value: 'Fully' }],
    seller: { name: 'Sunil Negi', type: 'Owner', avatar: '', verified: true }
  }
];

export const TESTIMONIALS: Testimonial[] = [
  { id: '1', name: 'Sanjay Rawat', city: 'Dehradun', propertyType: '2BHK Apartment', quote: "Found my dream home in just two days! The Property Pal's verified listings saved me so much time.", rating: 5 },
  { id: '2', name: 'Dr. Anjali Gupta', city: 'Delhi', propertyType: 'Residential Villa', quote: "Professional service and transparent pricing. Highly recommended for premium properties.", rating: 5 },
  { id: '3', name: 'Vikram Mehta', city: 'Mumbai', propertyType: 'Commercial Shop', quote: "The workspace listings are top-notch. I found a great office at IT Park Dehradun thanks to them.", rating: 5 }
];
